"""pedidos_grupo

Revision ID: 0d06d3fed374
Revises: 57bd92671284
Create Date: 2026-05-08 01:36:56.189034
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# Identificadores de revisión usados por Alembic.
revision: str = '0d06d3fed374'
down_revision: str | None = '57bd92671284'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pedidos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('grupo', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('nota', sa.String(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completado_en', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pedidos_creado_en'), ['creado_en'], unique=False)
        batch_op.create_index(batch_op.f('ix_pedidos_estado'), ['estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_pedidos_grupo'), ['grupo'], unique=False)

    op.create_table('pedido_ninos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('nino_id', sa.Integer(), nullable=True),
    sa.Column('nino_nombre', sa.String(), nullable=False),
    sa.Column('transaccion_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['nino_id'], ['ninos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaccion_id'], ['transacciones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pedido_ninos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pedido_ninos_nino_id'), ['nino_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pedido_ninos_pedido_id'), ['pedido_id'], unique=False)

    op.create_table('pedido_lineas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pedido_nino_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=True),
    sa.Column('producto_nombre', sa.String(), nullable=False),
    sa.Column('producto_precio', sa.Float(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('reemplazo_texto', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['pedido_nino_id'], ['pedido_ninos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pedido_lineas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pedido_lineas_pedido_nino_id'), ['pedido_nino_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido_lineas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pedido_lineas_pedido_nino_id'))

    op.drop_table('pedido_lineas')
    with op.batch_alter_table('pedido_ninos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pedido_ninos_pedido_id'))
        batch_op.drop_index(batch_op.f('ix_pedido_ninos_nino_id'))

    op.drop_table('pedido_ninos')
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pedidos_grupo'))
        batch_op.drop_index(batch_op.f('ix_pedidos_estado'))
        batch_op.drop_index(batch_op.f('ix_pedidos_creado_en'))

    op.drop_table('pedidos')
    # ### end Alembic commands ###
