"""imagen_producto

Revision ID: 57bd92671284
Revises: 0002_categoria_producto
Create Date: 2026-05-07 22:38:13.337606
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# Identificadores de revisión usados por Alembic.
revision: str = '57bd92671284'
down_revision: str | None = '0002_categoria_producto'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagen', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_column('imagen')

    # ### end Alembic commands ###
